config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dinosaurs do
    resources :bookings, only: :create
    resources :reviews, only: :create
  end

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get "dashboard", to: 'pages#dashboard'
  patch 'bookings/:id/accept', to: 'bookings#accept', as: :acceptbooking
  patch 'bookings/:id/deny', to: 'bookings#deny', as: :denybooking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dinosaur
  validates :start_date, presence: true
  validates :end_date, presence: true


end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_address_name_species_and_character,
    against: {
      address: 'A',
      name: 'B',
      species: 'C',
      character: 'D'
    },
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    self.bookings.pluck(:rating) / self.bookings.length
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dinosaur
  validates :content, length: {minimum: 3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dinosaurs
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Unauthorized action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
    @bookings = Booking.all
  end

  # def show
  #   @dinosaur = Dinosaur.find(params[:id])
  #   @booking = Booking.new
  #   authorize @booking

  #   # @booking = Booking.find(params[:id])
  # end

  def create
    @booking = Booking.new(bookings_params)
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
    authorize @booking
    authorize @dinosaur

    @booking.user = current_user #pour démo, User par défaut. Il faudra remettre current_user pour confirmer le login
    @booking.dinosaur = @dinosaur
    @booking.status = "Pending"
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status: 'Accepted')
    redirect_to dashboard_path
  end

  def deny
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status: 'Denied')
    redirect_to dashboard_path
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create]

  def new
    @dinosaur = Dinosaur.new
    authorize @dinosaur
  end

  def create
    @dinosaur = Dinosaur.new(dinosaurs_params)
    @dinosaur.user = User.first #pour démo, User par défaut. Il faudra remettre current_user pour confirmer le login
    authorize @dinosaur
    if @dinosaur.save
      redirect_to dinosaur_path(@dinosaur)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @dinosaurs = policy_scope(Dinosaur)
    if params[:search].present?
      @dinosaurs = Dinosaur.search_by_address_name_species_and_character(params[:search][:query])
    else
      @dinosaurs = Dinosaur.all
    end
    @markers = @dinosaurs.geocoded.map do |dinosaur|
      {
        lat: dinosaur.latitude,
        lng: dinosaur.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {dinosaur: dinosaur}),
        marker_html: render_to_string(partial: "marker", locals: {dinosaur: dinosaur})
      }
    end
  end

  def show
    @dinosaur = Dinosaur.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    authorize @dinosaur
    authorize @booking
    @markers =
      [{
        lat: @dinosaur.latitude,
        lng: @dinosaur.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {dinosaur: @dinosaur}),
        marker_html: render_to_string(partial: "marker", locals: {dinosaur: @dinosaur})
      }]
  end

  def edit
    @dinosaur = Dinosaur.find(params[:id])
    authorize @dinosaur
  end

  def update
    @dinosaur = Dinosaur.find(params[:id])
    authorize @dinosaur
    @dinosaur.update(dinosaurs_params)
    redirect_to dinosaur_path(@dinosaur)
  end

  def destroy
    @dinosaur = Dinosaur.find(params[:id])
    authorize @dinosaur
    @dinosaur.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def dinosaurs_params
    params.require(:dinosaur).permit(:name, :species, :age, :weight, :height, :character, :address, :element, :price, :photo, :review, :rating, :user_id)
  end

  def booking_reference
    @booking_ref = @dinosaur.booking_ref
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @dinosaurs = Dinosaur.all.first(3)
  end

  def dashboard
    @dinosaurs = current_user.dinosaurs
    @bookings = current_user.bookings
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
    @review = Review.new(review_params)
    @review.dinosaur = @dinosaur
    respond_to do |format|
      authorize @review
      if @review.save
        format.html { redirect_to dinosaur_path(@dinosaur) }
        format.json
      else
        format.html { render "dinosaurs/show", status: :unprocessable_entity }
        format.json
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= link_to "New booking", new_booking_path if policy(Booking).new? %>

app/views/dinosaurs/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/dinosaurs/_info_window.html.erb
<div class="container-info-window avatar_large">
  <h4><%= dinosaur.name %></h4>
  <p><%= dinosaur.address %></p>
  <%= cl_image_tag dinosaur.photo.key, crop: :fill, class: :avatar, height: 40 %>
</div>

app/views/dinosaurs/_marker.html.erb
  <%= image_tag "Symbol-jp.svg", height: 50, width: 50, alt: "LogoDino" %>

app/views/dinosaurs/_review.html.erb
<p><%= review.content %></p>

app/views/dinosaurs/edit.html.erb
<div class="container-new d-grid gap-2">
  <h2 class="mb-2">Edit your Dino's profile <i class="fa-solid fa-paw"></i></h2>
  <hr />
  <%= simple_form_for(@dinosaur) do |f| %>
    <%= f.input :name %> <%= f.input :species %>
    <%= f.input :age, placeholder: 'M years old' %>
    <%= f.input :weight, placeholder: 'tonne' %>
    <%= f.input :height, placeholder: 'km' %>
    <%= f.input :character%>
    <%= f.input :address%>
    <%= f.input :element, collection: ["earth", "water", "wind", "fire"] %>
    <%= f.input :price, placeholder: '€'%>
    <%= f.input :photo, as: :file %>
    <div class="d-grid mt-3 btn btn-new">
    <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/dinosaurs/index.html.erb
<div class="container">
  <div class ="row justify-content-around">
    <div class="col-6">
      <div class="flash-success alert alert-dismissible fade show position-sticky mt-3" role="alert">
        <span><strong>Yay!</strong> 🦕 <%= @dinosaurs.count %> available dinosaurs around you ! </span>
        <a data-bs-dismiss="alert" aria-label="Close">
          <i class="fas fa-times"></i>
        </a>
      </div>
      <% @dinosaurs.each do |dino| %>
        <%= link_to dinosaur_path(dino) do %>
          <div class="card-dino-index my-3">
            <% if dino.photo.attached? %>
                <%= cl_image_tag dino.photo.key, crop: :fill%>
            <% end %>

            <div class="card-dino-infos-index">
              <div>
                <h2><%= dino.name%></h2>
                  <ul>
                    <li><strong>Species : </strong><%= dino.species%></li>
                    <li><strong>Character : </strong><%= dino.character%></li>
                  </ul>
              </div>

            <div>
              <h2 id="card-dino-pricing">€<%= dino.price%>/day</h2>
              <ul class="list-inline">
                <li class="list-inline-item"><i class="fa-regular fa-heart"></i></li>
                <li class="list-inline-item"><i class="fa-solid fa-star"></i><%= dino.rating%></li>
              </ul>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-5" id="indexmap">
      <div style="width: 100%; height: 100vh; border-radius:5px; position:sticky; top:90px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/dinosaurs/new.html.erb
<div class="div-form-top">
  <h2 class="mb-2">Create your Dino's profile <i class="fa-solid fa-paw"></i></h2>
</div>

<div class="div-form-body">
  <%= simple_form_for(@dinosaur) do |f| %>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name %>
      </div>
      <div class="col-md-6">
        <%= f.input :species %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :age, placeholder: 'M years old' %>
      </div>
      <div class="col-md-6">
        <%= f.input :weight, placeholder: 'tonne' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :height, placeholder: 'km' %>
      </div>
      <div class="col-md-6">
        <%= f.input :character%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :element, collection: ["earth", "water", "wind", "fire"] %>
      </div>
      <div class="col-md-6">
      <%= f.input :price, placeholder: '€'%>
        </div>
      </div>
      <div class="row">
        <%= f.input :address, placeholder: 'example: 1 Street NameStreet ZipCode Paris'%>
      </div>
      <div class="row">
        <%= f.input :photo, as: :file %>
      </div>
      <div class="row btn-new">
        <%= f.button :submit %>
      </div>
  <% end %>
</div>

app/views/dinosaurs/show.html.erb
<div class = "container">
  <div class ="row mt-3 mb-3">
    <div class="col-9">
      <%= cl_image_tag @dinosaur.photo.key, crop: :fill, class: :profile_picture %>
      <div class = "row justify-content-start align-items-center">
        <h1 class="col-10 mb-3 mt-3"><%=@dinosaur.name%>, the <%=@dinosaur.species.capitalize%></h1>
        <h3 class="col mb-3 mt-3 justify-content-right">⭐ <%= @dinosaur.rating%>/5</h3>
      </div>
        <ul class="list-group list-group-horizontal">
          <li class="list-group-item">
          <% if @dinosaur.element == "air"  %>
              <span><i class="fa-solid fa-wind"></i> <%= @dinosaur.element.capitalize %></span>
            <% elsif @dinosaur.element == "earth"%>
              <span><i class="fa-solid fa-mountain-sun"></i> <%= @dinosaur.element.capitalize %></span>
            <% else %>
              <span><i class="fa-solid fa-water"></i> <%= @dinosaur.element.capitalize %></span>
            <% end %>
          </li>
          <li class="list-group-item">
            <span><i class="fa-solid fa-clock"></i> <%= @dinosaur.age %> M years</span>
          </li>
          <li class="list-group-item">
            <span><i class="fa-solid fa-weight-scale"></i> <%= @dinosaur.weight %> kg</span>
          </li>
          <li class="list-group-item">
            <span><i class="fa-solid fa-ruler-vertical"></i> <%= @dinosaur.height %> meters</span>
          </li>
          <li class="list-group-item">
            <span><i class="fa-solid fa-heart-circle-exclamation"></i> <%= @dinosaur.character.capitalize %></span>
          </li>
        </ul>
        <div class="text-divider">
          <hr class="rounded mt-3">
        </div>
      <div class="row mb-10">
            <div data-controller="insert-in-list" data-insert-in-list-position-value="afterbegin">
              <div data-insert-in-list-target="items">
                <% if @dinosaur.reviews.blank? %>
                  <p> Be the first to leave a review for <%= @dinosaur.name %></p>
                <% else %>
                  <% @dinosaur.reviews.each do |review| %>
                      <div class="row align-items-center mb-3 mt-3">
                        <div class="col-6">
                          <div class = "row align-items-baseline">
                            <p class="col text-justify"><%= review.content %></p>
                          </div>
                        </div>
                      </div>
                  <% end %>
                <% end %>
              </div>
              <%= simple_form_for([@dinosaur, @review],
                  data: {
                    insert_in_list_target: "form",
                    action: "submit->insert-in-list#send"
                  }) do |f|
                %>
                <div class="row align-items-center mb-3 mt-3">
                      <div class="col-12">
                        <div class = "row justify-content-center">
                          <%= f.input :content, class:"w-100"%> <%= f.button :submit, class:"btn btn-flat"%>
                        </div>
                      </div>
                    </div>
              <% end %>
            </div>
      </div>
      <div class="text-divider mt-3">
        <hr class="rounded">
      </div>
      <h6><i class="fa-solid fa-binoculars mt-2 mb-2"></i> Where can I find <%= @dinosaur.name%>?</h6>
      <div style="width: 800px; height: 400px; border-radius:5px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="col-3 p-4" id="bookingform">
      <div class="mb-6">
          <div class="row align-items-center">
              <h3 class="col-4"><%= @dinosaur.price %>€</h3>
              <h6 class="col-4">per day</h6>
          </div>
          <div class="row align-items-center">
              <h6 class="col-4">⭐ <strong><%= @dinosaur.rating %>/5</strong></h6>
              <h6 class="col-6"><%= pluralize @dinosaur.reviews.size, "review" %></h6>
          </div>

          <hr class="rounded mt-3 mb-3">
          <div>
              <%= simple_form_for [@dinosaur, @booking] do |f| %>
                <%= f.input :start_date %>
                <%= f.input :end_date %>
                <div class="d-grid gap-2 pt-3 mb-0">
                <%= f.submit "BOOK", class: "btn-new" %>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class = "container">
  <div class ="row mt-5">
    <div class="col-auto">
      <%= image_tag "avatar.svg", class: "avatar-large" %>
    </div>
    <div class="col">
      <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
      <p><%= current_user.email %></p>
    </div>
    <hr class="rounded my-5">
  </div>

<nav>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Booking requests</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">
        My Dinosaurs
        <span class="badge text-bg-secondary"><%= current_user.dinosaurs.count %></span>
      </button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="messages-tab" data-bs-toggle="tab" data-bs-target="#messages" type="button" role="tab" aria-controls="messages" aria-selected="false">
      My bookings
      <span class="badge text-bg-secondary"><%= current_user.bookings.count %></span>
      </button>
    </li>
  </ul>
</nav>

<div class="tab-content">
  <div class="tab-pane active" id="profile" role="tabpanel" aria-labelledby="profile-tab" tabindex="1">
      <div class="container my-3">
        <h6 class="mb-3"><strong>Pending Bookings</strong> <span class="badge bg-secondary">New</span></h6>
        <% current_user.dinosaurs.each do |dinosaur| %>
          <div class = "row ms-1">
            <% dinosaur.bookings.each do |booking|%>
              <% if booking.status == "Pending"%>
                <div class="alert alert-secondary" role="alert">
                  <p> Booking request from <%= booking.start_date%> to <%= booking.end_date %> for <strong><%= dinosaur.name%> the <%= dinosaur.species %></strong></p>
                  <%= link_to "Accept", acceptbooking_path(booking), class: "btn btn-danger", data: {turbo_method: :patch} %>
                  <%= link_to "Deny", denybooking_path(booking), class: "btn btn-success", data: {turbo_method: :patch} %>
                </div>
              <%end%>
            <%end%>
          </div>
        <%end%>
        <hr class="rounded my-3">
        <h6 class="mb-3"><strong>Accepted Bookings</strong></h6>
        <% current_user.dinosaurs.each do |dinosaur| %>
          <div class = "row ms-1">
            <% dinosaur.bookings.each do |booking|%>
              <% if booking.status == "Accepted"%>
                <div class="alert alert-secondary" role="alert">
                  <p> Booking request from <%= booking.start_date%> to <%= booking.end_date %> for <strong><%= dinosaur.name%> the <%= dinosaur.species %></strong></p>
                </div>
              <%end%>
            <%end%>
          </div>
        <%end%>
        <hr class="rounded my-3">
        <h6 class="mb-3"><strong>Denied Bookings</strong></h6>
        <% current_user.dinosaurs.each do |dinosaur| %>
          <div class = "row ms-1">
            <% dinosaur.bookings.each do |booking|%>
              <% if booking.status == "Denied"%>
                <div class="alert alert-secondary" role="alert">
                  <p> Booking request from <%= booking.start_date%> to <%= booking.end_date %> for <strong><%= dinosaur.name%> the <%= dinosaur.species %></strong></p>
                </div>
              <%end%>
            <%end%>
          </div>
        <%end%>
      </div>
  </div>
  <div class="tab-pane" id="home" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
    <div class ="row mt-3 justify-content-between">
      <div class = "container">
        <% current_user.dinosaurs.each do |dinosaur| %>
          <div class ="row">
            <div class="col-auto">
              <%= cl_image_tag dinosaur.photo.key, crop: :fill, class: :dashboard_picture %>
            </div>
            <div class ="col-auto">
              <h4><%=dinosaur.name%>, the <%=dinosaur.species.capitalize%> ⭐ <%= dinosaur.rating%>/5</h4>
              <ul class="list-group list-group-horizontal my-3">
                <li class="list-group-item">
                  <% if dinosaur.element == "air" %>
                    <span><i class="fa-solid fa-wind"></i> <%= dinosaur.element.capitalize %></span>
                  <% elsif dinosaur.element == "earth"%>
                    <span><i class="fa-solid fa-mountain-sun"></i> <%= dinosaur.element.capitalize %></span>
                  <% else %>
                    <span><i class="fa-solid fa-water"></i> <%= dinosaur.element.capitalize %></span>
                  <% end %>
                </li>
                <li class="list-group-item">
                  <span><i class="fa-solid fa-clock"></i> <%= dinosaur.age %> M years</span>
                </li>
                <li class="list-group-item">
                  <span><i class="fa-solid fa-weight-scale"></i> <%= dinosaur.weight %> kg</span>
                </li>
                <li class="list-group-item">
                  <span><i class="fa-solid fa-ruler-vertical"></i> <%= dinosaur.height %> meters</span>
                </li>
                <li class="list-group-item">
                  <span><i class="fa-solid fa-heart-circle-exclamation"></i> <%= dinosaur.character.capitalize %></span>
                </li>
              </ul>
              <div class="btn-group mt-2" role="group" aria-label="Basic example">
                <%= link_to "Profile", dinosaur_path(dinosaur), type:"button", class:"btn btn-flat"%>
                <%= link_to "Edit", edit_dinosaur_path(dinosaur), type:"button", class:"btn btn-flat"%>
                <%=link_to "Delete", dinosaur_path(dinosaur), data: {turbo_method: :delete, turbo_confirm: 'Are you certain you want to delete this dinosaur?'}, type:"button", class:"btn btn-flat"%>
              </div>
            </div>
            <hr class="text-divider my-4">
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab" tabindex="0">
    <div class="container my-3">
          <h6 class="mb-3"><strong>My Bookings</strong></h6>
          <% current_user.bookings.each do |booking| %>
          <div class ="row mt-3">
            <div class="col-auto">
              <%= cl_image_tag booking.dinosaur.photo.key, crop: :fill, class: :dashboard_picture %>
            </div>
            <div class ="col-auto">
              <h4 class="my-2"><%= booking.dinosaur.name %>, the <%=booking.dinosaur.species.capitalize%> ⭐ <%= booking.dinosaur.rating%>/5</h4>
              <div>
                <% if booking.status == "Pending"%>
                  <div class="alert alert-warning p-2 w-25" role="alert">
                    <%= booking.status %>
                  </div>
                <% elsif booking.status == "Accepted"%>
                  <div class="alert alert-success p-2 w-25" role="alert">
                    <%= booking.status %>
                  </div>
                <%else%>
                  <div class="alert alert-danger p-2 w-25" role="alert">
                    <%= booking.status %>
                  </div>
                <%end%>
              </div>
              <p class="my-4"><strong>From </strong><%= booking.start_date %> <strong> to </strong><%= booking.end_date %> </p>
            </div>
          </div>
          <hr class="text-divider my-2">
          <%end%>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.0)), url(<%= image_path 'jp_banner_2000x1000.jpg'%>);">
  <div class="container-banner">
    <h1>Welcome to <strong>Jurassic Paris</strong></h1>
    <p>Change your life style and feel the extraordinary</p>


    <%= simple_form_for :search, url: dinosaurs_path, method: :get do |f| %>
      <div class="search-form-control form-group", style="margin-bottom: 20px" >
        <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search for a dino nearby"/>
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex align-items-center container">
    <%= render "shared/card"  %>
      <%= link_to "Show more dinosaurs", dinosaurs_path, class: "btn-more mx-auto" %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ dinosaur, review ],
                    data: {
                      insert_in_list_target: "form",
                      action: "submit->insert-in-list#send"
                    }) do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top ">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Logo_JurassicParis.svg"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dinosaurs around me", dinosaurs_path, class: "nav-link" %>
          </li>
          <li class="nav-item-adopt">
            <%= link_to "Adopt a dinosaur", new_dinosaur_path, class: "btn-navbar" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Adopt a dinosaur", new_dinosaur_path, class: "dropdown-item" %>
              <%= link_to "Log out", new_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
          <li class="nav-item">
            <%= link_to "Dinosaurs around me", dinosaurs_path, class: "nav-link" %>
          </li>
          <li class="nav-item-adopt">
            <%= link_to "Adopt a dinosaur", new_dinosaur_path, class: "btn-navbar" %>
          </li>
          <%= link_to "Login", new_user_session_path, class: "btn-navbar-login" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>